// this code is automatically generated by frost

#ifndef FROST_HPP
#define FROST_HPP

namespace frost {

template <typename T> struct Meta;

template <typename Owner, typename T> struct Field
{
    char const *name;
    T Owner::*member;
    bool editable;
};

} // namespace frost

#include <tuple>

#endif


#endif
