// this code is automatically generated by frost

#ifndef FROST_HPP
#define FROST_HPP

namespace frost {

template <typename T> struct Meta;

template <typename Owner, typename T> struct Field
{
    char const *name;
    T Owner::*member;
    bool editable;
};

} // namespace frost

#include <tuple>

#endif


#ifndef FROST_META_DATA_EditorCamera
#define FROST_META_DATA_EditorCamera

#define FROST_BODY$EditorCamera friend struct frost::Meta<EditorCamera>;

#define FROST_DATA$EditorCamera \
template <> struct frost::Meta<wsp::EditorCamera> \
{ \
    using Type = wsp::EditorCamera; \
    static constexpr auto fields = std::make_tuple( \
     \
    ); \
}; 
#endif
